### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by toncho11** [pkoning2/lk201emu#1]
Hi,

Great project! I have one vt220 without a keyboard and I would like to make one.

But you use a USB converter from the keyboard's USB type A to the MicroUSB of the Adafruit Trinket M0, right? 

Do you have cards for sale?

**Comment by pkoning2** [comment]
Thanks Toncho!

I assume by "converter" you mean some sort of active device.  No, it doesn't need that.  All that is needed is a cable that goes between the two connector types.  Adafruit has one, it is mentioned in the documentation (emulator.md), https://www.adafruit.com/product/1099 .
I don't have cards for sale.  My intent was to provide the design, both software and hardware.  You can buy the board (bare board) from OSH Park at the link given in kicad.md, or you can use the kicad design files to create a board file for some other fab shop if you prefer.  The parts are available from many suppliers; I included a BOM link at Digikey, but you can use others if you prefer.  The assembly instructions are included in the documentation as well.  It's a pretty simple item, just barely harder than "Heathkit".  In particular, no surface-mount parts.  A simple hobbyist-grade small soldering iron and some electronic-grade rosin-core solder is really all you need.

**Comment by toncho11** [comment]
Hi again,

I got my card and I soldered the capacitors and resistors already. One thing is that there is not much space between the legs for the capacitors and especially for the transistor and the voltage regulator. One needs a good soldering station with a thin head. I soldered two legs together at some point. 

**Question 1:** 
Is it possible to re-program the Adafruit Trinket while soldered? With the Arduino this is not the case because it does not accept a new program if the RX pin is connected to something. I will need to do adjustments in the code as my terminal is not a regular one. It has a modified ROM for my native language. So can you apply changes while it is already soldered? Maybe I should use a socket?

**Question 2:** 
Is ICL3232CPZ identical to ICL3232CP (without the "Z") because I can not find cheaply (or at all) ICL3232CPZ.
Here is a datasheet: https://www.renesas.com/us/en/document/dst/icl3221-icl3222-icl3223-icl3232-icl3241-icl3243-datasheet
I am thinking of getting this one: https://www.ebay.fr/itm/114270364057

Thanks again for the project. I am advancing.

**Comment by pkoning2** [comment]
Yes, the Trinket can be reprogrammed while soldered.  See the instructions in doc/software.md, section "Loading software".  This works because on the Trinket the programming operation does not use the UART, instead it uses the USB.

You mention that you have a "modified ROM".  Do you mean you have a terminal that uses a non-English LK201, for example the French (AZERTY) layout?  That does not make any difference.  The LK201 keycodes are for the key locations, so the keycode that is Q on the English model is used for A on the French one.  The handling of the different keyboard layouts is in the terminal microcode, not in the keyboard.  That does mean, of course, that you need a USB keyboard with the French layout if you have a terminal that wants a French LK201.  If you want to use an English layout USB keyboard for use with a French terminal, then yes, you'd have to change the translation table in my program so that -- for example -- the USB keystroke for the letter A is sent as the LK201 keycode for Q.

I have the Renesas RS232 part, which I get from Digikey -- a USA based distributor that has good prices, as does Mouser (also in the USA).  I don't know about similar companies in Europe, but I would expect they exist.  I would guess the CP would be comparable.  The main question is whether the pin assignment matches.  I would expect it does, normally the pins are standard and later versions of the same circuit use the same definitions.

**Comment by toncho11** [comment]
No, it is not French, but Bulgarian. Actually I am not sure what to expect as I have not seen it in operation. It displays things in English, but with Cyrillic alphabet ...

Digikey in Europe can cost a lot for delivery (usually 20 euros) and then you might have import taxes of unknown value that you pay at delivery ... One guy says that for 52 euros of purchase he got 32 euros of additional taxes from UPS ...

**Comment by pkoning2** [comment]
Toncho, I did not mean to suggest using Digikey if you're outside north America.  I understand the problem of shipping and taxes.  My idea was that I would expect companies similar to Digikey (electronic parts distributors) to exist in other parts of the world.  If there is one in the EU that would be a much better option for you.  Ebay is fine too, if the parts you get that way are real.
On the keyboard: if the terminal expects an LK201, the emulator should work.  A given key on your USB keyboard would have display the same way on that terminal as the corresponding key location does on a real LK201 keyboard.  If you don't know exactly what the layout should look like, the best answer is to use the existing software to start, and then test with that to see if any changes are needed.  The conversion from USB codes to LK201 codes comes from the usb_lk201 table in lk201.ino, you can change that to be any mapping you want, then rebuild and reload using the instructions in doc/software.md.

**Comment by toncho11** [comment]
Here is a comparison:

![ICL3232](https://user-images.githubusercontent.com/1851997/116736640-724fa700-a9f0-11eb-85a3-cb9a6ece78d9.png)

There is only 1 driver in the no Z version. Would this be a problem? Also size is a bit different.

**Comment by pkoning2** [comment]
That is very strange.  I've searched for the ICL3232CP and as far as I can tell it is simply the same as the CPZ except that the CPZ is lead-free.  Certainly that's what the Renesas data sheets I have found tell me.
I can't see the information you posted.  Can you look at the data sheet referenced in the CP column and post it here?  I can look at it.  But it sounds like what you have there is not a real ICL3232CP.  I also don't know what it means to have an RS232 "transceiver".  It may be compatible, or not.
Your best solution is to search for another supplier who can sell you an actual ICL232CPZ.  Or any other 16-bit 2rx 2tx RS232 chip that has the same pinout.  It's a standard design, I'm sure there are other suppliers.  Just make sure that it handles 3.3 volt supply, 3.3 volt I/O, and has the correct pinout.

**Comment by toncho11** [comment]
I got it from mouser.fr. It allows you to compare two products. The datasheets provided for the two are identical:
https://www.mouser.fr/datasheet/2/308/DTC124E_D-1773603.pdf

**Comment by pkoning2** [comment]
Interesting.  I think Mouser is simply wrong, and the explanation is what I said: the CP is simply the older non-RoHS version of the CPZ.  So use either one.

**Comment by toncho11** [comment]
MAX3232ECPE looks pin compatible. It is also 2rx 2tx. I can buy it from ebay/aliexpress without an expensive delivery.

**Comment by pkoning2** [comment]
No, it's not.  That is an 18 pin device, not 16 pin.  You could certainly modify the design to use it, but the existing schematic and board won't work for that.

**Comment by toncho11** [comment]
I do not see a pdip version with 18 pins in the specification. It says pdip 16?

https://eu.mouser.com/datasheet/2/256/MAX3222E-MAX3246E-349176.pdf

**Comment by pkoning2** [comment]
You're right, my mistake.  I looked in the wrong spot.  I agree with you, that is a compatible part, it should work.

**Comment by toncho11** [comment]
Hi,

For the PS1420 I already have a piezo beeper from another project: 

Tension: 3,5 à 5,0 volts.
- Consommation: <25 ma.
- Fréquence: 2300 hz (+/- 500 hz).
- Puissance sonore: 85 dB minimum à 10cm.

It has + and - though. How should I put it?

**Comment by pkoning2** [comment]
You're talking about the USB version, right?  Pin 1, on the left (near the Arduino board) is the + terminal.

**Comment by toncho11** [comment]
Yes. USB. Thanks. It can be added on the board for the future versions :).

**Comment by pkoning2** [comment]
You mean add a + symbol?  Good idea, will do.

**Comment by toncho11** [comment]
Yes for the "+".

How did you solder the pins of the Adafruit chip? From both sides of your card?
These pins have a plastic part, did you remove it? 

I ordered the last parts I need to complete your card. :)

**Comment by pkoning2** [comment]
I soldered the pins only from the back of the board and the top of the Trinket.  Left the plastic in place.  I never solder things from both sides, because the solder reaches both sides anyway thanks to the plated through holes.

**Comment by toncho11** [comment]
![Uploading IMG_20210715_202506.jpg…]()

This is the final product.

**Comment by toncho11** [comment]
![IMG_20210715_202506](https://user-images.githubusercontent.com/1851997/125839887-cb3feaae-ec2c-4610-ae0c-41c49c14f1cb.jpg)

This is the final product. I will be able to test in two weeks though ... as my terminal is in another country :)

**Comment by pkoning2** [comment]
Looks good!
