### ISSUE TITLE
Install Adafruit libraries

### ISSUE THREAD

**Issue by toncho11** [pkoning2/lk201emu#2]
One needs to install additional libraries from GitHub for the code to compile for the USB version:

* https://github.com/adafruit/Adafruit_ASFcore
* https://github.com/adafruit/Adafruit_DotStar

It is not only https://github.com/adafruit/Adafruit_ZeroTimer

otherwise it gives errors during compilation.

**Comment by pkoning2** [comment]
You're right, it looks like I need to add that to software.md.

**Comment by pkoning2** [comment]
I install these things through the Arduino SDK Library Manager.  That shows ZeroTimer and DotStar -- yes, I forgot DotStar.  It doesn't show ASFcore, and the documentation seems to say it should be installed automatically as part of some of the other libraries.

**Comment by pkoning2** [comment]
Documentation has been updated.
