### ISSUE TITLE
Lk-201 to (->)  ps/2 or usb is real?

### ISSUE THREAD

**Issue by shrshnka** [pkoning2/lk201emu#7]
Hey, is it real to convert lk-201 signals to ps/2  to use it on a regular PC?

**Comment by pkoning2** [comment]
No, this device is for the other direction: PS/2 (or USB) keyboard emulating an LK201 for use with DEC devices that need an LK201 keyboard.
I think it would be possible for the same hardware to go in the other direction, but that needs completely different firmware and I have not made any attempt to do that.

**Comment by shrshnka** [comment]
Thank you
